INSERT INTO "NOTICE_CATEGORY" (NOTICECATEGORYGUID, NOTICETYPE, NOTICETYPENAME, SHOWORDER, SENDTYPE, SENDINTERVAL) VALUES ('CB3B73D9250359ABAETHDA81BE621561', 'IllegalDailyStatistics', '每日违法检测提醒', '26', 'Web', '0');
INSERT INTO SYS_DB_VERSION(UPDATEDID,APVERSION,SQLDESCRIPTION,UPDATEDTIME) 
VALUES(APP_DB_VERSION_ID_SEQ.NEXTVAL,'20170707.251','增加每日违法检测提醒消息类型',SYSDATE);
commit;
exit;
